// qwik/src/index.ts
import { component$, useSignal, useVisibleTask$ } from '@builder.io/qwik';
import { Observable } from 'rxjs';

export const useBloc = <D, E>(subject: Observable<D>, initialValue?: D) => {
	const data = useSignal<D | null>(initialValue || null);
	const loading = useSignal<boolean>(initialValue === undefined);
	const error = useSignal<E | null>(null);

	useVisibleTask$(() => {
		const subscription = subject.subscribe({
			next: (newData) => {
				data.value = newData;
				loading.value = false;
				error.value = null;
			},
			error: (err) => {
				data.value = null;
				loading.value = false;
				error.value = err;
			},
			complete: () => {
				loading.value = false;
			},
		});

		return () => subscription.unsubscribe();
	});

	return { data, loading, error };
};

// solid/src/index.ts
import { createSignal, createEffect, onCleanup } from "solid-js";
import { Observable, Subscription } from "rxjs";

/**
 * Creates a Solid.js hook that connects to an RxJS observable.
 *
 * @template D - The type of data.
 * @template E - The type of error.
 * @param subject - The RxJS observable.
 * @param initialValue - Initial value for the state.
 */
export function useBloc<D, E>(subject: Observable<D>, initialValue?: D) {
	const [data, setData] = createSignal<D | null>(initialValue || null);
	const [loading, setLoading] = createSignal<boolean>(initialValue === undefined);
	const [error, setError] = createSignal<E | null>(null);

	let subscription: Subscription;

	createEffect(() => {
		subscription = subject.subscribe({
			next: (newData: D) => {
				setData(newData);
				setLoading(false);
				setError(null);
			},
			error: (err: E) => {
				setData(null);
				setLoading(false);
				setError(err);
			},
			complete: () => {
				setLoading(false);
			}
		});
	});

	onCleanup(() => {
		subscription.unsubscribe();
	});

	return { data, loading, error };
}
